export interface PriceItem {
  name: string;
  full: number;
  collaborator: number;
}

export const eurofarmaPrices: PriceItem[] = [
  { name: "Manicure completa", full: 45, collaborator: 22.5 },
  { name: "Pedicure completa", full: 50, collaborator: 25 },
  { name: "Escova - cabelo longo", full: 120, collaborator: 60 },
  { name: "Lavagem", full: 50, collaborator: 25 },
  { name: "Virilha Completa (3 serviços)", full: 109, collaborator: 54.5 },
  { name: "Completa (buço, axila, perna inteira, íntima)", full: 260, collaborator: 130 },
  { name: "Corte Feminino", full: 242, collaborator: 121 },
  { name: "Corte masculino", full: 110, collaborator: 55 },
  { name: "Manicure masculino", full: 46, collaborator: 23 },
  { name: "Secar", full: 72, collaborator: 36 },
  { name: "Axila - F", full: 44, collaborator: 22 },
  { name: "Axila - M", full: 44, collaborator: 22 },
  { name: "Pedicure Francesinha", full: 54, collaborator: 27 },
  { name: "Buço (cera)", full: 39, collaborator: 19.5 },
  { name: "Meia perna F", full: 90, collaborator: 45 },
  { name: "Meia perna M", full: 110, collaborator: 55 },
  { name: "Esmaltação Francesinha Decorada (adicional)", full: 38, collaborator: 19 },
  { name: "Esmaltação dos pés", full: 34, collaborator: 17 },
  { name: "Escova - cabelo médio (nível dos ombros)", full: 100, collaborator: 50 },
  { name: "Lavar e Secar", full: 70, collaborator: 35 },
  { name: "Escova - cabelo curto", full: 96, collaborator: 48 },
  { name: "Virilha (1 serviço) simples", full: 72, collaborator: 36 },
  { name: "Perna inteira F", full: 130, collaborator: 65 },
  { name: "Perna inteira M", full: 150, collaborator: 75 },
  { name: "Queixo F", full: 44, collaborator: 22 },
  { name: "Queixo M", full: 42, collaborator: 21 },
  { name: "Braços F", full: 66, collaborator: 33 },
  { name: "Costas M", full: 110, collaborator: 55 },
  { name: "Braços M", full: 66, collaborator: 33 },
  { name: "Rosto F", full: 99, collaborator: 49.5 },
  { name: "Design de sobrancelha", full: 68, collaborator: 34 },
  { name: "Corte Máquina Masculino", full: 80, collaborator: 40 },
  { name: "Corte Feminino Franja", full: 64, collaborator: 32 },
  { name: "Prancha (adicional, qualquer tamanho)", full: 50, collaborator: 25 },
  { name: "Prancha acompanhada de Escova (a depender)", full: 160, collaborator: 80 },
  { name: "Esmaltação mãos", full: 34, collaborator: 17 },
  { name: "Esmaltação Decorada", full: 38, collaborator: 19 },
  { name: "Esmaltação Francesinha Decorada (mão)", full: 38, collaborator: 19 },
  { name: "Manicure sem esmaltação (cutícula/lixar/massagem)", full: 46, collaborator: 23 },
  { name: "Pedicure completa com Francesinha Decorada", full: 55, collaborator: 27.5 },
  { name: "Pedicure masculino", full: 52, collaborator: 26 },
  { name: "Pedicure sem esmaltação (cutícula/lixar/massagem)", full: 50, collaborator: 25 },
  { name: "Nádegas", full: 64, collaborator: 32 },
  { name: "Virilha Íntima (2 serviços)", full: 109, collaborator: 54.5 },
  { name: "Barriga F", full: 59, collaborator: 29.5 },
  { name: "Dedos dos pés ou mãos F", full: 44, collaborator: 22 },
  { name: "Barriga M", full: 70, collaborator: 35 },
  { name: "Tórax", full: 90, collaborator: 45 },
  { name: "Rosto com cera hipoalergênica", full: 99, collaborator: 49.5 },
  { name: "Dedos dos pés ou mãos (depilação)", full: 44, collaborator: 22 },
  { name: "Coloração de sobrancelha (Henna) - sem design", full: 60, collaborator: 30 },
  { name: "Completa (1/2 perna + virilha íntima com nádegas)", full: 260, collaborator: 130 },
  { name: "Design de sobrancelha (com pinça)", full: 68, collaborator: 34 },
];