project_id = "uwcjtomxzlmqsffjqxlg"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.vertice-login-code]
    verify_jwt = false
